### ISSUE TITLE
US_airline_tweets.csv

### ISSUE THREAD

**Issue by roqueleal** [maxxx580/twitter-sentiment-analysis#1]
A great job, I would consider including the jupyter nootbook to extract the file US_airline_tweets.csv
it would be very useful to have this

All the best

**Comment by maxxx580** [comment]
It is already in the data cleaning section. or do you mean the script to extract the file from Twitter ?

**Comment by roqueleal** [comment]
Exactly, it will be very useful to have the tweets extraction script, thanks for your answer

**Comment by maxxx580** [comment]
the dataset comes from kaggle in this case (see link below). I am actually working on a [twitter infinite crawler](https://github.com/maxxx580/infinite-twitter-crawler) . It should be ready soon. 
https://www.kaggle.com/crowdflower/twitter-airline-sentiment

**Comment by roqueleal** [comment]
A great job, thanks for sharing
